[package]
name = "wafer"
description = "WAFER: WebAssembly Forth Engine in Rust - CLI REPL and compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
wafer-core = { path = "../core", version = "0.2.6" }
wasmtime = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
rustyline = "18"
