[package]
name = "wafer-web"
description = "WAFER: WebAssembly Forth Engine in Rust - browser bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.cargo-machete]
ignored = ["wafer-core"]

[lints]
workspace = true

[dependencies]
wafer-core = { path = "../core", version = "0.1.0" }
